In [24]:
import numpy as np
import json
from keras.utils.np_utils import to_categorical
import time

In [25]:
with open('training_data.json') as json_file:
    training = json.load(json_file)

In [26]:
training

{'boards': [[0, 0, 0, 0, 0, 0, 0, -1, 0],
  [0, 0, 0, 0, 0, 0, 1, -1, -1],
  [0, -1, 0, 0, 1, 0, 1, -1, -1],
  [0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, -1, 0, 0, 0, 1, 0],
  [0, 0, -1, -1, 0, 0, 1, 1, 0],
  [0, 0, -1, -1, 0, 1, 1, 1, -1],
  [-1, 0, -1, -1, 1, 1, 1, 1, -1],
  [0, 0, 0, -1, 0, 0, 0, 0, 0],
  [0, 0, -1, -1, 1, 0, 0, 0, 0],
  [0, 0, -1, -1, 1, 0, -1, 1, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0],
  [1, 0, 0, 0, 0, -1, 0, 0, 0],
  [1, 0, 1, 0, 0, -1, 0, -1, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, -1],
  [1, 0, 0, 0, 0, -1, 0, 0, -1],
  [1, 0, 0, 0, 0, -1, 1, -1, -1],
  [1, 1, 0, -1, 0, -1, 1, -1, -1],
  [0, 0, 0, 0, 0, 0, -1, 0, 0],
  [0, -1, 0, 1, 0, 0, -1, 0, 0],
  [1, -1, 0, 1, 0, -1, -1, 0, 0],
  [1, -1, -1, 1, 1, -1, -1, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0],
  [1, -1, 0, 0, 0, 0, 0, 0, 0],
  [1, -1, 0, 1, 0, 0, -1, 0, 0],
  [1, -1, 0, 1, 1, 0, -1, -1, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, -1, 0, 0, 1, 0, 0, 0, 0],
  [1, -1, 0, -1, 1, 0, 0, 0, 0],
  [1, -1, 1, -1, 1, 0, 0, 0, -1],
  [

In [27]:
len(training['boards'])

176427

In [28]:
x_train = np.array(training['boards'])

In [29]:
one_hot_moves = to_categorical(training['moves'])

In [30]:
x_val = x_train[:20000]
partial_x_train = x_train[20000:]

y_val = one_hot_moves[:20000]
partial_y_train = one_hot_moves[20000:]

In [31]:
from keras import models
from keras import layers
from keras import optimizers
from keras import losses
from keras import metrics

model = models.Sequential()

model.add(layers.Dense(81, activation = 'relu', input_shape = (9,)))
model.add(layers.Dense(81, activation = 'relu', input_shape = (9,)))
model.add(layers.Dense(81, activation = 'relu', input_shape = (9,)))
model.add(layers.Dense(9, activation = 'softmax'))



model.compile(optimizer = 'rmsprop',
             loss = 'categorical_crossentropy',
             metrics = ['accuracy'])


# train the network
now = time.time()

history = model.fit(partial_x_train,
                   partial_y_train,
                   epochs=10,
                   batch_size = 512,
                   validation_data = (x_val, y_val))

print(time.time()-now)

# print(model.evaluate(x_test, one_hot_test_labels))

Train on 156427 samples, validate on 20000 samples
Epoch 1/10
156427/156427 [==============================] - 2s 14us/step - loss: 1.8055 - acc: 0.3104 - val_loss: 1.6230 - val_acc: 0.3376
Epoch 2/10
156427/156427 [==============================] - 2s 12us/step - loss: 1.5691 - acc: 0.3369 - val_loss: 1.5630 - val_acc: 0.3326
Epoch 3/10
156427/156427 [==============================] - 2s 13us/step - loss: 1.5449 - acc: 0.3371 - val_loss: 1.5468 - val_acc: 0.3364
Epoch 4/10
156427/156427 [==============================] - 2s 12us/step - loss: 1.5366 - acc: 0.3390 - val_loss: 1.5506 - val_acc: 0.3358
Epoch 5/10
156427/156427 [==============================] - 2s 12us/step - loss: 1.5321 - acc: 0.3391 - val_loss: 1.5371 - val_acc: 0.3353
Epoch 6/10
156427/156427 [==============================] - 2s 12us/step - loss: 1.5287 - acc: 0.3398 - val_loss: 1.5405 - val_acc: 0.3328
Epoch 7/10
156427/156427 [==============================] - 2s 12us/step - loss: 1.5263 - acc: 0.3406 - val_loss: 1

In [33]:
model.predict(np.array([[0,0,0,0,0,0,0,0,0]]))

array([[0.1068257 , 0.10285925, 0.11283226, 0.09752862, 0.13472906,
        0.11168992, 0.11965717, 0.09989714, 0.11398092]], dtype=float32)

In [34]:
model.predict(np.array([[1,-1,0
                         ,1,0,0
                         ,0,-1,0]]))

array([[0.00069154, 0.00126763, 0.154369  , 0.00335905, 0.3193573 ,
        0.1803657 , 0.20868352, 0.00111358, 0.13079268]], dtype=float32)

In [37]:
### the above move prediction isn't bad, but it blocks instead of going for the win

In [38]:
model.save('both_players_model.h5')

In [39]:
from keras.models import load_model
test_model = load_model('both_players_model.h5')

In [41]:
test_model.predict(np.array([[0,0,0,0,0,0,0,0,0]]))

array([[0.1068257 , 0.10285925, 0.11283226, 0.09752862, 0.13472906,
        0.11168992, 0.11965717, 0.09989714, 0.11398092]], dtype=float32)

In [42]:
model.predict(np.array([[1,0,0
                         ,1,0,0
                         ,0,0,0]]))

array([[0.0029699 , 0.17244734, 0.18158871, 0.00924262, 0.08385083,
        0.09035493, 0.02769546, 0.36179483, 0.07005534]], dtype=float32)

In [43]:
model.predict(np.array([[1,0,0
                         ,0,1,0
                         ,0,0,0]]))

array([[0.01054975, 0.16563588, 0.1606006 , 0.09419075, 0.00045154,
        0.10965849, 0.06616875, 0.29826596, 0.09447826]], dtype=float32)

In [55]:
current_board = [[0,0,0],[0,0,0],[0,0,0]]

def board_to_prediction_list(board):
    vector_board = []
    for row in board:
        vector_board += row
    np_board = np.array([vector_board])

    return list(model.predict(np_board)[0])

def make_prediction(predicted_moves, available_moves):
    
    while True:
        move = predicted_moves.index(max(predicted_moves))
        predicted_moves[move] = 0

        if move in available_moves:
            return move

pred_list = board_to_prediction_list(current_board)
print(pred_list)
my_move = make_prediction(pred_list,set([3,5,6,7,8]))
print(my_move)

[0.12536095, 0.10221725, 0.11943597, 0.09634156, 0.13534363, 0.0961914, 0.1141284, 0.11071, 0.10027086]
6


In [47]:
predicted_moves.index(max(predicted_moves))

4