In [1]:
import numpy as np
import json
from keras.utils.np_utils import to_categorical
import time

Using TensorFlow backend.


In [2]:
with open('random_ai_training_data.json') as json_file:
    training = json.load(json_file)

In [4]:
x_train = np.array(training['boards'])

In [6]:
one_hot_moves = to_categorical(training['moves'])

In [10]:
x_val = x_train[:10000]
partial_x_train = x_train[10000:]

y_val = one_hot_moves[:10000]
partial_y_train = one_hot_moves[10000:]

In [20]:
from keras import models
from keras import layers
from keras import optimizers
from keras import losses
from keras import metrics

model = models.Sequential()

model.add(layers.Dense(81, activation = 'relu', input_shape = (9,)))
model.add(layers.Dense(81, activation = 'relu', input_shape = (9,)))
model.add(layers.Dense(81, activation = 'relu', input_shape = (9,)))
model.add(layers.Dense(9, activation = 'softmax'))



model.compile(optimizer = 'rmsprop',
             loss = 'categorical_crossentropy',
             metrics = ['accuracy'])


# train the network
now = time.time()

history = model.fit(partial_x_train,
                   partial_y_train,
                   epochs=10,
                   batch_size = 512,
                   validation_data = (x_val, y_val))

print(time.time()-now)

# print(model.evaluate(x_test, one_hot_test_labels))

Train on 52037 samples, validate on 10000 samples
Epoch 1/10
52037/52037 [==============================] - 1s 12us/step - loss: 2.0635 - acc: 0.2393 - val_loss: 1.9133 - val_acc: 0.3082
Epoch 2/10
52037/52037 [==============================] - 0s 6us/step - loss: 1.8009 - acc: 0.3158 - val_loss: 1.7234 - val_acc: 0.3133
Epoch 3/10
52037/52037 [==============================] - 0s 6us/step - loss: 1.6716 - acc: 0.3206 - val_loss: 1.6442 - val_acc: 0.3113
Epoch 4/10
52037/52037 [==============================] - 0s 6us/step - loss: 1.6172 - acc: 0.3179 - val_loss: 1.6156 - val_acc: 0.3120
Epoch 5/10
52037/52037 [==============================] - 0s 6us/step - loss: 1.5930 - acc: 0.3191 - val_loss: 1.5972 - val_acc: 0.3154
Epoch 6/10
52037/52037 [==============================] - 0s 5us/step - loss: 1.5805 - acc: 0.3193 - val_loss: 1.5947 - val_acc: 0.3119
Epoch 7/10
52037/52037 [==============================] - 0s 6us/step - loss: 1.5747 - acc: 0.3211 - val_loss: 1.5857 - val_acc: 0.31

In [34]:
model.predict(np.array([[0,0,0,0,0,0,0,0,0]]))

array([[0.12536095, 0.10221725, 0.11943597, 0.09634156, 0.13534363,
        0.0961914 , 0.1141284 , 0.11071   , 0.10027086]], dtype=float32)

In [37]:
model.predict(np.array([[1,-1,0,1,0,0,0,-1,0]]))

array([[0.0025964 , 0.00089522, 0.12145222, 0.00356799, 0.42681354,
        0.13180692, 0.16103035, 0.00157205, 0.15026526]], dtype=float32)

In [39]:
model.save('random_model.h5')

In [40]:
from keras.models import load_model
test_model = load_model('random_model.h5')

In [41]:
test_model.predict(np.array([[0,0,0,0,0,0,0,0,0]]))

array([[0.12536095, 0.10221725, 0.11943597, 0.09634156, 0.13534363,
        0.0961914 , 0.1141284 , 0.11071   , 0.10027086]], dtype=float32)

In [55]:
current_board = [[0,0,0],[0,0,0],[0,0,0]]

def board_to_prediction_list(board):
    vector_board = []
    for row in board:
        vector_board += row
    np_board = np.array([vector_board])

    return list(model.predict(np_board)[0])

def make_prediction(predicted_moves, available_moves):
    
    while True:
        move = predicted_moves.index(max(predicted_moves))
        predicted_moves[move] = 0

        if move in available_moves:
            return move

pred_list = board_to_prediction_list(current_board)
print(pred_list)
my_move = make_prediction(pred_list,set([3,5,6,7,8]))
print(my_move)

[0.12536095, 0.10221725, 0.11943597, 0.09634156, 0.13534363, 0.0961914, 0.1141284, 0.11071, 0.10027086]
6


In [47]:
predicted_moves.index(max(predicted_moves))

4