In [16]:
import numpy as np
import json
from keras.utils.np_utils import to_categorical
import time
from sklearn.model_selection import train_test_split

In [17]:
with open('Random_Random.json') as json_file:
    RR_training = json.load(json_file)
    
with open('Random_Smart.json') as json_file:
    RS_training = json.load(json_file)
    
with open('Smart_Random.json') as json_file:
    SR_training = json.load(json_file)

In [18]:
for item in [RR_training, RS_training, SR_training]:
    print(len(item['moves']))
    print(len(item['boards']))

70866
70866
131987
131987
134993
134993


In [19]:
training = {'boards': [], 'moves': []}
for dictionary in [RR_training, RS_training, SR_training]:
    for key, value in dictionary.items():
        training[key] += value

In [20]:
len(training['boards'])

337846

In [21]:
134993+131987+70866

337846

In [24]:
X = np.array(training['boards'])
y = to_categorical(training['moves'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size=0.2, random_state=42)

In [25]:
for i in [X_train, X_test, X_val, y_train, y_test, y_val]:
    print(len(i))

270276
54056
13514
270276
54056
13514


In [57]:
# this model isn't so great
# I used the one further down
from keras import models
from keras import layers
from keras import optimizers
from keras import losses
from keras import metrics

model = models.Sequential()

model.add(layers.Dense(9, activation = 'relu', input_shape = (9,)))
model.add(layers.Dense(9, activation = 'relu'))
model.add(layers.Dense(9, activation = 'relu'))
model.add(layers.Dense(9, activation = 'relu'))
model.add(layers.Dense(9, activation = 'relu'))
model.add(layers.Dense(9, activation = 'relu'))
model.add(layers.Dense(9, activation = 'relu'))
model.add(layers.Dense(9, activation = 'relu'))
model.add(layers.Dense(9, activation = 'relu'))
model.add(layers.Dense(9, activation = 'softmax'))



model.compile(optimizer = 'rmsprop',
             loss = 'categorical_crossentropy',
             metrics = ['accuracy'])


# train the network
now = time.time()

history = model.fit(X_train,
                   y_train,
                   epochs=30,
                   batch_size = 512,
                   validation_data = (X_test, y_test))

print(time.time()-now)

print(model.evaluate(X_val, y_val))

Train on 270276 samples, validate on 54056 samples
Epoch 1/30
270276/270276 [==============================] - 3s 11us/step - loss: 1.8903 - acc: 0.3468 - val_loss: 1.6265 - val_acc: 0.4374
Epoch 2/30
270276/270276 [==============================] - 2s 9us/step - loss: 1.4852 - acc: 0.5167 - val_loss: 1.3902 - val_acc: 0.5493
Epoch 3/30
270276/270276 [==============================] - 2s 9us/step - loss: 1.3328 - acc: 0.5643 - val_loss: 1.2758 - val_acc: 0.5816
Epoch 4/30
270276/270276 [==============================] - 2s 9us/step - loss: 1.2541 - acc: 0.5899 - val_loss: 1.2143 - val_acc: 0.6122
Epoch 5/30
270276/270276 [==============================] - 2s 9us/step - loss: 1.2075 - acc: 0.6191 - val_loss: 1.1969 - val_acc: 0.6279
Epoch 6/30
270276/270276 [==============================] - 2s 9us/step - loss: 1.1747 - acc: 0.6361 - val_loss: 1.1597 - val_acc: 0.6535
Epoch 7/30
270276/270276 [==============================] - 2s 9us/step - loss: 1.1508 - acc: 0.6468 - val_loss: 1.1351 

In [55]:
model.predict(np.array([[0,0,0,0,0,0,0,0,0]]))

array([[0.02178787, 0.02496707, 0.0257297 , 0.02728997, 0.78476787,
        0.03005825, 0.0259759 , 0.02616759, 0.03325576]], dtype=float32)

In [56]:
model.predict(np.array([[1,-1,0
                         ,1,0,0
                         ,0,-1,0]]))

array([[0.1683737 , 0.05102368, 0.08542217, 0.04528546, 0.22401215,
        0.06745588, 0.0763906 , 0.13408835, 0.14794804]], dtype=float32)

In [45]:
test_model.predict(np.array([[1,-1,0
                         ,1,0,0
                         ,0,-1,0]]))

array([[0.00043794, 0.00052062, 0.21343212, 0.00179795, 0.2019275 ,
        0.16881675, 0.31666756, 0.00581618, 0.09058337]], dtype=float32)

In [47]:
model.predict(np.array([[1,-1,0
                         ,0,1,0
                         ,0,-1,0]]))

array([[0.00325159, 0.00093395, 0.19345361, 0.16106528, 0.00418115,
        0.12907228, 0.23651929, 0.00877786, 0.26274502]], dtype=float32)

In [48]:
test_model.predict(np.array([[1,-1,0
                         ,0,1,0
                         ,0,-1,0]]))

array([[1.1218474e-05, 3.7624336e-06, 3.2174754e-01, 3.4098116e-01,
        5.0292820e-05, 2.4599876e-01, 3.2355905e-02, 1.3134971e-04,
        5.8719952e-02]], dtype=float32)

In [50]:
model.predict(np.array([[1,0,0
                         ,0,1,0
                         ,0,0,0]]))

array([[2.5778514e-04, 2.6437433e-02, 1.2027474e-01, 5.6764647e-02,
        5.4575043e-04, 9.6586965e-02, 2.5654316e-01, 1.6845371e-01,
        2.7413586e-01]], dtype=float32)

In [51]:
test_model.predict(np.array([[1,0,0
                         ,0,1,0
                         ,0,0,0]]))

array([[2.26156026e-05, 3.40315397e-03, 2.33651400e-02, 2.84878999e-01,
        9.09274968e-05, 2.25693494e-01, 5.71935624e-03, 1.10313356e-01,
        3.46512944e-01]], dtype=float32)

In [ ]:
### the above move prediction isn't bad, but it blocks instead of going for the win

In [35]:
from keras.models import load_model
test_model = load_model('smart_model.h5')

In [36]:
test_model.predict(np.array([[0,0,0,0,0,0,0,0,0]]))

array([[0.02982613, 0.02642992, 0.04474984, 0.04018626, 0.70327   ,
        0.04147457, 0.03849569, 0.03270375, 0.04286384]], dtype=float32)

In [37]:
model.predict(np.array([[1,0,0
                         ,1,0,0
                         ,0,0,0]]))

array([[0.00406162, 0.01751591, 0.04555007, 0.00840351, 0.17237176,
        0.21559587, 0.06073135, 0.2012618 , 0.27450812]], dtype=float32)

In [ ]:
model.predict(np.array([[1,0,0
                         ,0,1,0
                         ,0,0,0]]))

In [ ]:
current_board = [[0,0,0],[0,0,0],[0,0,0]]

def board_to_prediction_list(board):
    vector_board = []
    for row in board:
        vector_board += row
    np_board = np.array([vector_board])

    return list(model.predict(np_board)[0])

def make_prediction(predicted_moves, available_moves):
    
    while True:
        move = predicted_moves.index(max(predicted_moves))
        predicted_moves[move] = 0

        if move in available_moves:
            return move

pred_list = board_to_prediction_list(current_board)
print(pred_list)
my_move = make_prediction(pred_list,set([3,5,6,7,8]))
print(my_move)

In [ ]:
predicted_moves.index(max(predicted_moves))

In [58]:
# this is the model I used
from keras import models
from keras import layers
from keras import optimizers
from keras import losses
from keras import metrics

model = models.Sequential()

model.add(layers.Dense(729, activation = 'relu', input_shape = (9,)))
model.add(layers.Dense(729, activation = 'relu'))
model.add(layers.Dense(729, activation = 'relu'))
model.add(layers.Dense(81, activation = 'relu'))
model.add(layers.Dense(81, activation = 'relu'))
model.add(layers.Dense(81, activation = 'relu'))
model.add(layers.Dense(9, activation = 'softmax'))



model.compile(optimizer = 'rmsprop',
             loss = 'categorical_crossentropy',
             metrics = ['accuracy'])


# train the network
now = time.time()

history = model.fit(X_train,
                   y_train,
                   epochs=10,
                   batch_size = 512,
                   validation_data = (X_test, y_test))

print(time.time()-now)

print(model.evaluate(X_val, y_val))

Train on 270276 samples, validate on 54056 samples
Epoch 1/10
270276/270276 [==============================] - 4s 14us/step - loss: 0.7634 - acc: 0.7829 - val_loss: 0.6116 - val_acc: 0.8221
Epoch 2/10
270276/270276 [==============================] - 3s 12us/step - loss: 0.6117 - acc: 0.8220 - val_loss: 0.6114 - val_acc: 0.8216
Epoch 3/10
270276/270276 [==============================] - 3s 12us/step - loss: 0.5977 - acc: 0.8235 - val_loss: 0.6125 - val_acc: 0.8229
Epoch 4/10
270276/270276 [==============================] - 3s 12us/step - loss: 0.5911 - acc: 0.8245 - val_loss: 0.6060 - val_acc: 0.8199
Epoch 5/10
270276/270276 [==============================] - 4s 14us/step - loss: 0.5870 - acc: 0.8252 - val_loss: 0.5926 - val_acc: 0.8232
Epoch 6/10
270276/270276 [==============================] - 3s 12us/step - loss: 0.5846 - acc: 0.8258 - val_loss: 0.5970 - val_acc: 0.8223
Epoch 7/10
270276/270276 [==============================] - 3s 12us/step - loss: 0.5818 - acc: 0.8260 - val_loss: 0

In [59]:
model.save('smart_model.h5')